runtime: python311
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_APP: "app.py"
  # Set these in the GCP console or via secrets
  # STRIPE_SECRET_KEY: "..."
  # META_APP_ID: "..."

# Optional: Add handlers if you have static files to serve
handlers:
- url: /static
  static_dir: frontend/static
- url: /.*
  script: auto
